package net.opatry.nanoc.kt.dsl

import net.opatry.nanoc.kt.core.ContextProvider
import net.opatry.nanoc.kt.core.Item
import net.opatry.nanoc.kt.core.Repository
import java.io.File

class RouteRule(
    private val repository: Repository,
    val pattern: String,
    val run: RouteRule.(item: Item) -> String? = { it.identifier.toString() }
): Rule(), ContextProvider by repository, (Item) -> File? {

    override fun invoke(item: Item): File? {
        try {
            val outputPath = run(item) ?: return null
            val outputFile = File(repository.outputDir, outputPath.removePrefix("/"))
            outputFile.parentFile.mkdirs()
            if (item.isBinary) {
                // FIXME should we really consider "compiledContent" as a path to file?
                // FIXME how nanoc is dealing with .yaml associated to .jpeg?
                with(File(item.rawFileName)) {
                    if (exists()) {
                        copyTo(outputFile, overwrite = true)
                    } else {
                        // FIXME how can be possible otherwise? bug?
                        return null
                    }
                }
            } else {
                // TODO be smart if it's a route generated by a passthrough rule, copyTo is enough, no need to writeText nor deal with binary item
                outputFile.writeText(item.compiledContent)
            }
            return outputFile
        } finally {
            // FIXME routed state should be stored in item
            repository.routed(item)
        }
    }
}